# docker build -t nibata-app/celery-worker:0.0.1 -f images/Dockerfile-Celery-Worker .
FROM python:3.11-slim
LABEL authors="nbacquet"

RUN rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin
RUN apt-get update

WORKDIR /app

COPY . /app/

RUN pip install -r requirements.txt

ENTRYPOINT ["celery", "-A", "modules.my_tasks:celery_app", "worker", "--loglevel=INFO"]